# -*- coding: utf-8 -*-
"""flower_classification_ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AesofAcj-EixAFQrRIc6WAKrvjsr28AQ
"""

!pip install ucimlrepo
!pip install tensorflow

from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)



from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
from sklearn.model_selection import train_test_split



feature_columns = ["sepal length", "sepal width", "petal length", "petal width"]
label_column = "class"
label_mapping = {"Iris-setosa": 0, "Iris-versicolor": 1, "Iris-virginica": 2}

X_ = X[feature_columns]
Y_ = y[label_column].map(label_mapping)
Y_

X_train, X_test, y_train, y_test = train_test_split(X_, Y_)

category_count = Y_.value_counts()
category_count

model = keras.Sequential([layers.Dense(16, activation="relu"), layers.Dense(16, activation="relu"), layers.Dense(3, activation="softmax")])
model.compile(
    optimizer = 'adam',
    loss = 'sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train, y_train, epochs=32, batch_size=32)

results = model.evaluate(X_test, y_test)
results

model.predict(X_test)

X_test

y_test